INSERT INTO tbl_slots (level, section, slot_number, vehicle_id, time_in, time_out)
VALUES 
-- Level 1
(1, 'A', 1, NULL, NULL, NULL),
(1, 'A', 2, NULL, NULL, NULL),
(1, 'A', 3, NULL, NULL, NULL),
(1, 'A', 4, NULL, NULL, NULL),
(1, 'A', 5, NULL, NULL, NULL),
(1, 'A', 6, NULL, NULL, NULL),
(1, 'A', 7, NULL, NULL, NULL),
(1, 'A', 8, NULL, NULL, NULL),
(1, 'A', 9, NULL, NULL, NULL),
(1, 'A', 10, NULL, NULL, NULL),

(1, 'B', 1, NULL, NULL, NULL),
(1, 'B', 2, NULL, NULL, NULL),
(1, 'B', 3, NULL, NULL, NULL),
(1, 'B', 4, NULL, NULL, NULL),
(1, 'B', 5, NULL, NULL, NULL),
(1, 'B', 6, NULL, NULL, NULL),
(1, 'B', 7, NULL, NULL, NULL),
(1, 'B', 8, NULL, NULL, NULL),
(1, 'B', 9, NULL, NULL, NULL),
(1, 'B', 10, NULL, NULL, NULL),

(1, 'C', 1, NULL, NULL, NULL),
(1, 'C', 2, NULL, NULL, NULL),
(1, 'C', 3, NULL, NULL, NULL),
(1, 'C', 4, NULL, NULL, NULL),
(1, 'C', 5, NULL, NULL, NULL),
(1, 'C', 6, NULL, NULL, NULL),
(1, 'C', 7, NULL, NULL, NULL),
(1, 'C', 8, NULL, NULL, NULL),
(1, 'C', 9, NULL, NULL, NULL),
(1, 'C', 10, NULL, NULL, NULL),

-- Level 2
(2, 'A', 1, NULL, NULL, NULL),
(2, 'A', 2, NULL, NULL, NULL),
(2, 'A', 3, NULL, NULL, NULL),
(2, 'A', 4, NULL, NULL, NULL),
(2, 'A', 5, NULL, NULL, NULL),
(2, 'A', 6, NULL, NULL, NULL),
(2, 'A', 7, NULL, NULL, NULL),
(2, 'A', 8, NULL, NULL, NULL),
(2, 'A', 9, NULL, NULL, NULL),
(2, 'A', 10, NULL, NULL, NULL),

(2, 'B', 1, NULL, NULL, NULL),
(2, 'B', 2, NULL, NULL, NULL),
(2, 'B', 3, NULL, NULL, NULL),
(2, 'B', 4, NULL, NULL, NULL),
(2, 'B', 5, NULL, NULL, NULL),
(2, 'B', 6, NULL, NULL, NULL),
(2, 'B', 7, NULL, NULL, NULL),
(2, 'B', 8, NULL, NULL, NULL),
(2, 'B', 9, NULL, NULL, NULL),
(2, 'B', 10, NULL, NULL, NULL),

(2, 'C', 1, NULL, NULL, NULL),
(2, 'C', 2, NULL, NULL, NULL),
(2, 'C', 3, NULL, NULL, NULL),
(2, 'C', 4, NULL, NULL, NULL),
(2, 'C', 5, NULL, NULL, NULL),
(2, 'C', 6, NULL, NULL, NULL),
(2, 'C', 7, NULL, NULL, NULL),
(2, 'C', 8, NULL, NULL, NULL),
(2, 'C', 9, NULL, NULL, NULL),
(2, 'C', 10, NULL, NULL, NULL),

-- Level 3
(3, 'A', 1, NULL, NULL, NULL),
(3, 'A', 2, NULL, NULL, NULL),
(3, 'A', 3, NULL, NULL, NULL),
(3, 'A', 4, NULL, NULL, NULL),
(3, 'A', 5, NULL, NULL, NULL),
(3, 'A', 6, NULL, NULL, NULL),
(3, 'A', 7, NULL, NULL, NULL),
(3, 'A', 8, NULL, NULL, NULL),
(3, 'A', 9, NULL, NULL, NULL),
(3, 'A', 10, NULL, NULL, NULL),

(3, 'B', 1, NULL, NULL, NULL),
(3, 'B', 2, NULL, NULL, NULL),
(3, 'B', 3, NULL, NULL, NULL),
(3, 'B', 4, NULL, NULL, NULL),
(3, 'B', 5, NULL, NULL, NULL),
(3, 'B', 6, NULL, NULL, NULL),
(3, 'B', 7, NULL, NULL, NULL),
(3, 'B', 8, NULL, NULL, NULL),
(3, 'B', 9, NULL, NULL, NULL),
(3, 'B', 10, NULL, NULL, NULL),

(3, 'C', 1, NULL, NULL, NULL),
(3, 'C', 2, NULL, NULL, NULL),
(3, 'C', 3, NULL, NULL, NULL),
(3, 'C', 4, NULL, NULL, NULL),
(3, 'C', 5, NULL, NULL, NULL),
(3, 'C', 6, NULL, NULL, NULL),
(3, 'C', 7, NULL, NULL, NULL),
(3, 'C', 8, NULL, NULL, NULL),
(3, 'C', 9, NULL, NULL, NULL),
(3, 'C', 10, NULL, NULL, NULL);