CREATE DATABASE DB_PARCHEGGIAMO;

USE DB_PARCHEGGIAMO;

CREATE TABLE tbl_accounts (
    UID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    USERNAME VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    GENDER VARCHAR(10),
    PHONE VARCHAR(30),
    PASSWORD VARCHAR(50),
    ACCOUNT_TYPE VARCHAR(10),
    LICENCE VARCHAR(255) NULL
);

CREATE TABLE tbl_vehicles (
    VEHICLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    UID INT,
    PLATE_NUMBER VARCHAR(10),
    VEHICLE_TYPE_ID VARCHAR(20),
);

CREATE TABLE tbl_file_types (
    FILE_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    FILE_TYPE VARCHAR(50)
);

CREATE TABLE tbl_uploads (
    UPLOAD_ID INT AUTO_INCREMENT PRIMARY KEY,
    UID INT,
    VEHICLE_ID INT NULL,
    FILE_TYPE_ID INT,
    UPLOADED_FILE VARCHAR(255)
);

CREATE TABLE tbl_hours (
    HOUR_ID INT AUTO_INCREMENT PRIMARY KEY,
    HOURS INT
);

CREATE TABLE tbl_vehicle_types (
    VEHICLE_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_TYPE VARCHAR(20)
);

CREATE TABLE tbl_rates (
    RATE_ID INT AUTO_INCREMENT PRIMARY KEY,
    HOURS_ID INT,
    VEHICLE_TYPE_ID VARCHAR(20),
    FEE INT
);

CREATE TABLE tbl_slots (
    SLOT_ID INT AUTO_INCREMENT PRIMARY KEY,
    LEVEL VARCHAR(2),
    SECTION VARCHAR(1),
    SLOT_NUMBER INT,
    VEHICLE_ID INT NULL,
    TIME_IN VARCHAR(20) NULL,
    TIME_OUT VARCHAR(20) NULL
);

CREATE TABLE tbl_payment_history (
    HISTORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    UID INT,
    SLOT_ID VARCHAR(7),
    VEHICLE_ID INT,
    TIME_IN VARCHAR(20),
    TIME_OUT VARCHAR(20),
    AMOUNT_TO_PAY INT,
    PAYMENT INT
);